### ISSUE TITLE
[main] Crear versión inicial de árboles de frontend y backend de la aplicación

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/casevault-main#1]
# Descripción general
Necesitamos la estructura inicial de árboles de _backend_ y _frontend_ en el repositorio. Hemos considerado que adoptar el frontend de cierto proyecto de YouTube clone (@jorgeplazadelosreyes, ¿cuál?) desarrollado con React 16 y express.js podría ser una buena idea para comenzar el desarrollo. Podríamos simplemente traer el frontend de proyecto a este repositorio, y tratar de actualizarlo a React 18.

Por otro lado, el backend sí requeriría un desarrollo nuevo en Rails 7. Habría que reimplementar los modelos, rutas y APIs que son los originalmente usados en el proyecto del YouTube clone.

La aplicación en el backend puede ser creada con Rails en modo de API. El nombre de la aplicación es CaseVault (pascal case), o case_vault (snake case).

**Comment by sofiagadea** [comment]
El frontend se creará en base al Youtube clone [https://github.com/manikandanraji/youtubeclone-frontend](url)
