### ISSUE TITLE
[main] Vídeos adjuntos a casos

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/casevault-main#26]
Necesitamos proveer una interfaz que permita agregar una lista de vídeos de YouTube adjuntos al caso. Esta interfaz debiera desplegar una lista de ítems/bloques de vídeo (URL del vídeo y su título + imagen carátula obtenida desde YT) hacia abajo que contengan los vídeos, y la posibilidad de agregar/quitar estos bloques. Para agregar un nuevo bloque, evitar lightboxes o modales, más bien, crear un nuevo bloque vacío en donde el usuario pueda ingresar la URL del vídeo.

Se podría hacer que el usuario pueda usar un título alternativo para el vídeo, sobreescribiendo el título de YT. Es decir, al ingresar la URL del vídeo, se cargan sus datos desde YT, pero el usuario puede editar el título y cambiarlo.

**Comment by claudio-alvarez** [comment]
Bosquejo de UI
![IMG_20240502_100340](https://github.com/EthicApp-Development/casevault-main/assets/752908/df234dd1-4f65-4ec5-a0d7-7f8d22fbebac)

**Comment by jorgeplazadelosreyes** [comment]
Formulario actual:
![image](https://github.com/EthicApp-Development/casevault-main/assets/80331241/fbf54d9c-cb4f-4f2c-8864-41a6ea259d5c)
