### ISSUE TITLE
[main] Mejorar layout de la aplicación - topbar

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/casevault-main#33]
Tenemos que mejorar la barra superior del layout de la aplicación. Que la barra se extienda por todo el ancho y "CaseVault" quede alineado a la izquierda con un pequeño margen.

<img width="1312" alt="Screenshot 2024-05-09 at 13 46 44" src="https://github.com/EthicApp-Development/casevault-main/assets/752908/225edd57-7bec-4518-b032-e6a1fff6d575">

**Comment by sofiagadea** [comment]
Solved in issue 34
